### ISSUE TITLE
KEGG enrichment analysis for gut microbiome

### ISSUE THREAD

**Issue by khemlalnirmalkar** [GuangchuangYu/enrichment4GTEx_clusterProfiler#1]
Hello Prof. Yu,
I find your clusterProfiler (http://yulab-smu.top/clusterProfiler-book/) a useful tool and tried to follow the tutorial.
Since i am working on the gut microbiome and have KEGG pathways for microbiota (mix of bacteria) but not for one bacteria and your tutorial mentioned assigning an organism which is not possible for me.
Please can you guide me on how can i use my KEGG data to do enrichment analysis for microbiota?
Many thanks,
Khem

**Comment by GuangchuangYu** [comment]
pls post your feature request to the `clusterProfiler` repo.
